### ISSUE TITLE
私人FM接口使用

### ISSUE THREAD

**Issue by klaxonz** [MakcRe/KuGouMusicApi#11]
**问题描述**
在多次调用私人 FM 接口时返回的歌曲大部分重复，尝试修改不同的参数，接口返回的歌曲也差不多

**复现代码**
```python
import time
import requests

base_url = 'http://localhost:3000'

# userid 是我自己的
headers = {
    "cookie": "userid=xxxxxxxx"
}
response = requests.post(f"{base_url}/personal/fm?timestamp={int(time.time())}&mode=normal&action=play&song_pool_id=1", headers=headers)
```
**希望结果**
是否能实现移动端私人FM的逻辑，切换歌曲能和之前的已播放的歌曲不重复

**Comment by MakcRe** [comment]
你尝试一下把 hash 和 playtime 也传参一下，看一下还会不会返回重复的

**Comment by klaxonz** [comment]
我试了一下，除了要加hash 、 playtime 、songid参数之外，还需要加一个remain_songcnt参数，避免每次调用此接口都返回推荐歌曲，remain_songcnt大于 4 时不会返回推荐歌曲

**Comment by klaxonz** [comment]
提了PR https://github.com/MakcRe/KuGouMusicApi/pull/12 ，接口添加了remain_songcnt参数

**Comment by MakcRe** [comment]
刚刚看了一下接口，确实更新了一些参数。代码合并了，重新拉取一些就行
