### ISSUE TITLE
请求URL链接时报【本次请求需要验证】

### ISSUE THREAD

**Issue by UPman24** [MakcRe/KuGouMusicApi#14]
{"fail_process":["pkg"],"errcode":20028,"status":2,"error":"本次请求需要验证"}

**Comment by MakcRe** [comment]
哪个接口？

**Comment by UPman24** [comment]
> 哪个接口？

根据观察，是获取歌曲URL链接的接口。我是昨天晚上1点多的时候发的请求，之后只要获取歌曲链接就报：本次请求需要验证；最后我进iOS酷狗应该是获取歌曲链接的时候跳转了一个滑动验证码界面，校验通过之后，程序也就没有这个“本次请求需要验证”了；

**Comment by UPman24** [comment]
/song/url?hash=xxx

**Comment by HaoTian22** [comment]
同，任意歌曲都会返回这个
而我进官方网站/客户端连验证码都没弹

**Comment by MakcRe** [comment]
这个刚刚测试了一下，在未登录状态下会提示 本次请求需要验证，登录后就会正常返回结果（需注意缓存，最好带上时间戳）

**Comment by MakcRe** [comment]
> 同，任意歌曲都会返回这个 而我进官方网站/客户端连验证码都没弹

这个刚刚测试了一下，在未登录状态下会提示 本次请求需要验证，登录后就会正常返回结果（需注意缓存，最好带上时间戳）
