### ISSUE TITLE
如何判断是否登录状态？

### ISSUE THREAD

**Issue by ibalbal** [MakcRe/KuGouMusicApi#16]
我调用登录接口，返回数据我也看了，也登陆了
但是我没看到返回的token 以及当前程序的登录状态

**Comment by MakcRe** [comment]
能不能看一下啊返回的数据，我这边测试是可以返回有token字段的

**Comment by ibalbal** [comment]
看到了，之前没注意需要调用两次

如何判断当前登录状态呢

**Comment by MakcRe** [comment]
这个就需自己实现了，只要token没有失效就证明登录是可用的

**Comment by MakcRe** [comment]
接口中有一个使用token和用户id登录接口，只要该接口能正常返回数据，基本确定该token还没失效
