### ISSUE TITLE
大佬，播放接口有没有

### ISSUE THREAD

**Issue by 13627491210** [MakcRe/KuGouMusicApi#2]

**Comment by MakcRe** [comment]
获取音乐URL的接口已添加

**Comment by 13627491210** [comment]
> 获取音乐URL的接口已添加

<img width="979" alt="image" src="https://github.com/MakcRe/KuGouMusicApi/assets/37203543/c7b3103e-0d7b-454d-adba-8291518534f6">

**Comment by 13627491210** [comment]
> 获取音乐URL的接口已添加

大佬，部署到服务器，然后调用登陆接口，登陆成功之后，再调用 播放接口就会报这个错。我在本地直接请求播放接口是成功的。大佬，麻烦看看

**Comment by MakcRe** [comment]
> > 获取音乐URL的接口已添加
> 
> 大佬，部署到服务器，然后调用登陆接口，登陆成功之后，再调用播放接口就会报这个错。我在本地直接请求播放接口是成功的。大佬，麻烦看看

你看一下 cookie 的 token 和 userid 是否正常，我重现了一下，发现 部分音乐不携带 token 和userid (也有可能是国外的IP会出现这样的情况) 会出现这样的情况

**Comment by 13627491210** [comment]
我部署到国内服务器也是这样的，我试了三首歌都是如此。 以下是hash。4EC10B1B7B9BEB2F0ADB89BBEC5F664B  8ADBCF1F9D4C265ACBA5F78056293480。

**Comment by 13627491210** [comment]
> > > 获取音乐URL的接口已添加
> > 
> > 
> > 大佬，部署到服务器，然后调用登陆接口，登陆成功之后，再调用播放接口就会报这个错。我在本地直接请求播放接口是成功的。大佬，麻烦看看
> 
> 你看一下 cookie 的 token 和 userid 是否正常，我重现了一下，发现 部分音乐不携带 token 和userid (也有可能是国外的IP会出现这样的情况) 会出现这样的情况

应该和国外没关系，我换了两台国内服务器都是如此，如果大佬有时间的话 我可以把我服务器地址给你看一下，最近在做demo，急需这个接口，辛苦大佬看看。 我Q 782572516

**Comment by MakcRe** [comment]
你可以尝试一下把仓库拉下来重新部署试一下，我现在没时间，还不行的话我看一下晚上有没有时间

**Comment by 13627491210** [comment]
> 你可以尝试一下把仓库拉下来重新部署试一下，我现在没时间，还不行的话我看一下晚上有没有时间

我就是这么部署的，麻烦大佬晚上看看

**Comment by MakcRe** [comment]
你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到

**Comment by 13627491210** [comment]
> 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到

大佬，我知道原因了，是那个ip 问题，if (ip) {
      headers['X-Real-IP'] = ip
      headers['X-Forwarded-For'] = ip
    }。 我把IP 换成::1. 就可以了。不知道是不是我服务器被监控了还是咋的，我之前服务器请求过酷狗接口。    然后我还有个部署问题，我试过 pm2 start app.ts 启动，不行。目前我是把 项目拷贝到 服务器上，然后运行 npm run dev 来测试接口的。

**Comment by 13627491210** [comment]
> 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到

大佬，可以写个部署到自己服务器的文档吗

**Comment by bylengfeng** [comment]
> > 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到
> 
> 大佬，可以写个部署到自己服务器的文档吗



> > 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到
> 
> 大佬，可以写个部署到自己服务器的文档吗



> > 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到
> 
> 大佬，可以写个部署到自己服务器的文档吗



> > 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到
> 
> 大佬，可以写个部署到自己服务器的文档吗



> > 你试一下 /song/url?hash=xxx&cookie=token=xxx;userid=xxx 这样能不能获取到
> 
> 大佬，可以写个部署到自己服务器的文档吗

宝塔有node环境直接装就可以了
