### ISSUE TITLE
酷狗概念版二维码登录

### ISSUE THREAD

**Issue by klaxonz** [MakcRe/KuGouMusicApi#20]
酷狗概念版版支持二维码登录吗？

**Comment by klaxonz** [comment]
还有另一个疑问，概念版是否支持微信登录。我使用扫码状态接口登录成功后，响应头中没看到有userid和token这两个cookie。

**Comment by MakcRe** [comment]
我这边测试过都能正常登录

**Comment by MakcRe** [comment]
但二维码登录要注意不要用 /login/qr/key 该接口 qrcode_img 字段下生成二维码数据，要么用 /login/qr/create 该接口生成的数据，或者自己拼接链接然后生成二维码，https://h5.kugou.com/apps/loginQRCode/html/index.html?qrcode=xxx , 这个是拼接链接

**Comment by klaxonz** [comment]
是我调用接口的问题。二维码登录没成功的原因，使用了/login/qr/key生成的二维码，应该使用/login/qr/create生成的二维码。微信登录没成功的原因，/login/wx/check 返回405后还需要调用 /login/openplat。
