### ISSUE TITLE
请问接口改成概念版是这样嘛?怎么登录后还是手机版的酷狗音乐接口呀?

### ISSUE THREAD

**Issue by 2900037917** [MakcRe/KuGouMusicApi#24]
![Screenshot_2024-06-03-05-14-42-768_mark.via.gp.jpg](https://github.com/MakcRe/KuGouMusicApi/assets/47325784/63a551cc-91f2-467d-8224-d42f64397519)

![Screenshot_2024-06-03-05-14-50-138_mark.via.gp.jpg](https://github.com/MakcRe/KuGouMusicApi/assets/47325784/cbab666d-3292-4462-8a43-e5c11365535d)

**Comment by MakcRe** [comment]
把他改成  platform=lite

**Comment by 2900037917** [comment]
> 把他改成  platform=lite

好的
