### ISSUE TITLE
专辑信息接口使用问题

### ISSUE THREAD

**Issue by klaxonz** [MakcRe/KuGouMusicApi#25]
获取专辑信息接口 /album 中的必选参数 fields 有哪些值，文档中好像没提到。

**Comment by MakcRe** [comment]
支持  trans_param,special_tag,authors,album_name,publish_date,cover,intro,publish_company,type,album_id,language_id,is_publish,heat,grade,quality,exclusive,grade_count,author_name,sizable_cover,language,category
，也可以不传，不过会有部分信息缺失

**Comment by klaxonz** [comment]
貌似不太行，fields字段传不传值，都没有返回数据
```json
{"status":1,"error_code":0,"errmsg":"","data":[{}]}
```
看了现在官方app用的是  /container/v1/album 这个接口

**Comment by klaxonz** [comment]
一切正常，传错参数了
