### ISSUE TITLE
歌曲成绩单api signature加密问题

### ISSUE THREAD

**Issue by 3642214** [MakcRe/KuGouMusicApi#28]
`https://gateway.kugou.com/grow/v1/song_ranking/play_page/ranking_info?album_audio_id=27518487&appid=1000&clienttime=1721551942&clientver=12349&dfid=33adKL3kCXiR0qZaXO0b6fwk&mid=e05adfc8235c8d0f855020cfe8955c33b0d90a0d&token=415915bf4c78f29e9fe4b0e49f00a55da2b0a35a15cea5c3624eafbb4768bcbc&userid=2232405315&uuid=e05adfc8235c8d0f855020cfe8955c33b0d90a0d&signature=5cf792754d0c733d498dcbc1ac6a112b`
入口在，app播放歌曲界面，点击详情 =》歌曲成绩单
使用几个加密算法都不对，对比了下其他api，参数少了 srcappid，求问这个的 signature 加密算法

**Comment by MakcRe** [comment]
你可以尝试一下把 srcappid 这个参数去掉试一下能否请求成功

**Comment by 3642214** [comment]
/song/ranking?album_audio_id=27360669 这接口可以获取到，这api是安卓里的？

**Comment by MakcRe** [comment]
对的

**Comment by MakcRe** [comment]
其实很多接口原版都带有 srcappid 这个参数，只不过暂时不知道这个参数的作用，我都暂时把着个参数给临时去掉了。 这样 signature 的加密方法不用重新搞了

**Comment by 3642214** [comment]
👌，谢谢
