### ISSUE TITLE
获取歌曲更多版本号，签名错误

### ISSUE THREAD

**Issue by 3642214** [MakcRe/KuGouMusicApi#29]
https://listkmrp3cdn.kugou.com/v2/audio_related/total?album_audio_id=379425036&appid=1000&area_code=1&clientver=12375&version=1&signature=b4e6e31faf5749fd485a8801193cd051
能帮忙看下吗

**Comment by MakcRe** [comment]
这个对应酷狗哪里的？

**Comment by 3642214** [comment]
歌曲列表 右边3点 弹出页面
![IMG_4458](https://github.com/user-attachments/assets/774f037d-5565-4991-995d-0e03412e5234)
![IMG_4459](https://github.com/user-attachments/assets/e5fa1994-2947-4a65-93da-dbb82bfd3239)

**Comment by 3642214** [comment]
这页面 还有个 K歌 上面的数字 加密方式也不一样 url query参数用的是sign

**Comment by MakcRe** [comment]
获取更多版本接口已经添加上去了，重新拉取一下代码就行

**Comment by 3642214** [comment]
> 获取更多版本接口已经添加上去了，重新拉取一下代码就行

完美！
还有这个显示K歌数量的接口。
https://acsing.service.kugou.com/sing7/listenguide/json/v2/cdn/listenguide/get_total_opus_num_v02.do?isteen=0&songId=42141328&usemkv=1&platform=2&singerName=%E5%91%A8%E6%9D%B0%E4%BC%A6&songHash=E8B9ACDAA9F62838FFB1B6D0AA01C7DB&version=12375&sign=5f3b1ea0834c3e83&appid=1000
用的sign 参数，能看下吗？

**Comment by MakcRe** [comment]
现在我暂时没有时间搞这个参数，这个接口可能要明天晚上才能搞出来

**Comment by MakcRe** [comment]
> > 获取更多版本接口已经添加了，重新取一下代码就行
> 
> 完美！ 还有这个显示K歌数量的接口。 [https://acsing.service.kugou.com/sing7/listenguide/json/v2/cdn/listenguide/get_total_opus_num_v02.do?isteen=0&songId=42141328&usemkv=1&platform=2&singerName= %E5%91%A8%E6%9D%B0%E4%BC%A6&songHash=E8B9ACDAA9F62838FFB1B6D0AA01C7DB&version=12375&sign=5f3b1ea0834c3e83&appid=1000](https://acsing.service.kugou.com/sing7/listenguide/json/v2/cdn/listenguide/get_total_opus_num_v02.do?isteen=0&songId=42141328&usemkv=1&platform=2&singerName=%E5%91%A8%E6%9D%B0%E4%BC%A6&songHash=E8B9ACDAA9F62838FFB1B6D0AA01C7DB&version=12375&sign=5f3b1ea0834c3e83&appid=1000) 用的sign参数，能看下吗？

这个接口更新了，重新拉取一下代码就行

**Comment by 3642214** [comment]
能用，只是文档 获取音乐伴奏信息 接口写错了 应该是  /audio/accompany/matching
<img width="703" alt="image" src="https://github.com/user-attachments/assets/56beb333-9adb-45b6-839b-a94aaf93666d">
