### ISSUE TITLE
获取音乐URL

### ISSUE THREAD

**Issue by super963883929** [MakcRe/KuGouMusicApi#3]
我登录了会员账号获取回来的vip音乐url只有一小部分

**Comment by MakcRe** [comment]
能不能发一下音乐的 hash

**Comment by super963883929** [comment]
822460A47E8725A6826C5940D4C0CEC0 任意一首vip歌曲都是一样的,只有前半部分能够播放,后面的放不了

**Comment by MakcRe** [comment]
我这边测试是可以正常使用的

**Comment by MakcRe** [comment]
非会员的状态下就只有只有一小部分可行

**Comment by super963883929** [comment]
我是kugou VIP，我并且用登录接口登录了，获取回来的vip音乐都是一小部分能听

**Comment by Mamong** [comment]
不错的项目，一直不知道v5的URL要怎么样的参数才对，一直报20016。楼主的项目能成功获得播放地址。
