### ISSUE TITLE
歌词翻译只附带在 krc 的歌词中吗？

### ISSUE THREAD

**Issue by Ferry-200** [MakcRe/KuGouMusicApi#32]
尝试了很多带翻译的歌曲，只在 krc 里面找到 language（里面有音译和汉译），lrc 里面则没有相关的内容。

**Comment by MakcRe** [comment]
应该是的， kugou 现在大部分歌曲都是用 krc 的歌词，几乎很少用到 lrc 歌词，也没找到 其他 lrc 歌词的接口，如果非要用 lrc 歌词建议直接用 krc 转成 lrc
