### ISSUE TITLE
没有接口的文档吗

### ISSUE THREAD

**Issue by shangxiaohe** [MakcRe/KuGouMusicApi#33]

**Comment by MakcRe** [comment]
[kugoumusicapi-docs.4everland.app](https://kugoumusicapi-docs.4everland.app/)

**Comment by shangxiaohe** [comment]
大佬回复的真快，我在项目里面也找到了文档。

**Comment by MakcRe** [comment]
刚好看到

**Comment by shangxiaohe** [comment]
> 刚好看到

刚试了一个，非会员好多都是获取不了播放地址的

**Comment by MakcRe** [comment]
建议使用概念版的接口，登陆后好像可以获取到大部分不超过 flac 音质的播放地址，如果还不行可以尝试 [领取 VIP](https://kugoumusicapi-docs.4everland.app/#/?id=%e9%a2%86%e5%8f%96-vip%ef%bc%88%e9%9c%80%e8%a6%81%e7%99%bb%e9%99%86%ef%bc%8c%e8%af%a5%e6%8e%a5%e5%8f%a3%e4%b8%ba%e6%b5%8b%e8%af%95%e6%8e%a5%e5%8f%a3%ef%bc%89) 这个接口后再获取

**Comment by shangxiaohe** [comment]
大佬，这个可以在Ubuntu服务器上部署吗
