### ISSUE TITLE
登录了，获取不到vip歌曲

### ISSUE THREAD

**Issue by UzumakiHan** [MakcRe/KuGouMusicApi#36]
![image](https://github.com/user-attachments/assets/ef50c439-fc58-4f53-8b47-6816b2751b50)

**Comment by MakcRe** [comment]
能否发一下登陆成功后返回的信息

**Comment by UzumakiHan** [comment]
{
    "data": {
        "is_vip": 0,
        "servertime": "2024-11-09 17:16:44",
        "roam_type": 0,
        "t1": "806c01c808f171b2e228970c74250c3b8cfac0f6f5b2d34488a2933afda3697b8eddf1b5e9ffd5d12bb3488ccc675a2f7b839987cc9a634728b75f3a0837e4caa23e7ff59e0045e51c39ecc244e4b94c",
        "reg_time": "2013-08-23 21:53:00",
        "vip_type": 0,
        "vip_begin_time": "2020-09-04 19:03:57",
        "userid": 370898940,
        "su_vip_end_time": "",
        "sex": 1,
        "user_type": 0,
        "username": "kgopen370898940",
        "qq": 1,
        "exp": 6088,
        "m_end_time": "2020-10-05 19:03:57",
        "score": 6088,
        "m_is_old": 0,
        "birthday": "1997-06-28",
        "arttoy_avatar": "",
        "totp_server_timestamp": 1731143804,
        "roam_end_time": "",
        "su_vip_begin_time": "",
        "roam_begin_time": "",
        "vip_end_time": "2020-10-05 19:03:57",
        "secu_params": "be2641d4b15b33b485509feb491367dfb420859ae8e3bafa8a81168182e965c228b5f1d79096f17d51a7935ca5071363a612efa0ed3b7c8e58a3979d53eefeb725ce6ae7f9668676d4f1dce4e5270eb1",
        "totp_key": "7NEFM6FZMR5TZWWSQII3R6ZLQEVACRWX",
        "nickname": "有心人",
        "mobile": 1,
        "user_y_type": 0,
        "vip_token": "",
        "bc_code": "",
        "m_type": 0,
        "roam_list": {},
        "m_begin_time": "2020-09-04 19:03:57",
        "pic": "http://imge.kugou.com/kugouicon/165/20170623/20170623154604217457.jpg",
        "su_vip_clearday": "",
        "t_expire_time": 1733735804,
        "su_vip_y_endtime": "",
        "birthday_mmdd": "0628",
        "y_type": 0,
        "wechat": 0,
        "token": "706efddcde901b0a5d84c1e0ea4e54f885d2c2a2f592afe546c71dd369e42125"
    },
    "status": 1,
    "error_code": 0
}

**Comment by UzumakiHan** [comment]
> 能否发一下登陆成功后返回的信息

{
    "data": {
        "is_vip": 0,
        "servertime": "2024-11-09 17:16:44",
        "roam_type": 0,
        "t1": "806c01c808f171b2e228970c74250c3b8cfac0f6f5b2d34488a2933afda3697b8eddf1b5e9ffd5d12bb3488ccc675a2f7b839987cc9a634728b75f3a0837e4caa23e7ff59e0045e51c39ecc244e4b94c",
        "reg_time": "2013-08-23 21:53:00",
        "vip_type": 0,
        "vip_begin_time": "2020-09-04 19:03:57",
        "userid": 370898940,
        "su_vip_end_time": "",
        "sex": 1,
        "user_type": 0,
        "username": "kgopen370898940",
        "qq": 1,
        "exp": 6088,
        "m_end_time": "2020-10-05 19:03:57",
        "score": 6088,
        "m_is_old": 0,
        "birthday": "1997-06-28",
        "arttoy_avatar": "",
        "totp_server_timestamp": 1731143804,
        "roam_end_time": "",
        "su_vip_begin_time": "",
        "roam_begin_time": "",
        "vip_end_time": "2020-10-05 19:03:57",
        "secu_params": "be2641d4b15b33b485509feb491367dfb420859ae8e3bafa8a81168182e965c228b5f1d79096f17d51a7935ca5071363a612efa0ed3b7c8e58a3979d53eefeb725ce6ae7f9668676d4f1dce4e5270eb1",
        "totp_key": "7NEFM6FZMR5TZWWSQII3R6ZLQEVACRWX",
        "nickname": "有心人",
        "mobile": 1,
        "user_y_type": 0,
        "vip_token": "",
        "bc_code": "",
        "m_type": 0,
        "roam_list": {},
        "m_begin_time": "2020-09-04 19:03:57",
        "pic": "http://imge.kugou.com/kugouicon/165/20170623/20170623154604217457.jpg",
        "su_vip_clearday": "",
        "t_expire_time": 1733735804,
        "su_vip_y_endtime": "",
        "birthday_mmdd": "0628",
        "y_type": 0,
        "wechat": 0,
        "token": "706efddcde901b0a5d84c1e0ea4e54f885d2c2a2f592afe546c71dd369e42125"
    },
    "status": 1,
    "error_code": 0
}

**Comment by MakcRe** [comment]
我看到你这个帐号是没有开通VIP的，你VIP是领取的还是在酷狗那里开通的

**Comment by MakcRe** [comment]
这个接口领取的VIP只能使用概念版的接口才能获取到url，普通版接口是获取不到的，

**Comment by MakcRe** [comment]
普通版接口的token是不通用的，更换接口版本后需要重新登陆

**Comment by UzumakiHan** [comment]
> 这个接口领取的VIP只能使用概念版的接口才能获取到url，普通版接口是获取不到的，

![image](https://github.com/user-attachments/assets/4642eed8-01f9-46e8-9076-d2b5e7ebd30d)
这个不是概念版的？

**Comment by UzumakiHan** [comment]
> 普通版接口的token是不通用的，更换接口版本后需要重新登陆

那要怎样才能获取到vip歌曲

**Comment by MakcRe** [comment]
![image](https://github.com/user-attachments/assets/9b7b4be0-a16b-4fe7-ac5b-c8b1dabff8de)

**Comment by MakcRe** [comment]
![image](https://github.com/user-attachments/assets/990d3081-bbba-4b4e-8383-a4c31780842a)
你看一下你的cookie KUGOU_API_PLATFORM 值是否为 lite

**Comment by MakcRe** [comment]
我看到你的为 undefined
![image](https://github.com/user-attachments/assets/557a9cc1-8993-48fa-87d8-4c905c8839fe)

**Comment by UzumakiHan** [comment]
> ![image](https://github.com/user-attachments/assets/990d3081-bbba-4b4e-8383-a4c31780842a)
> 你看一下你的cookie KUGOU_API_PLATFORM 值是否为 lite
> 

好的，忘记改成lite了，谢谢大佬。
