### ISSUE TITLE
打包后的exe通过脚本命令启动后获取url的接口无法获取vip音乐url

### ISSUE THREAD

**Issue by starfish122** [MakcRe/KuGouMusicApi#42]
直接双击打开打包后的exe可以正常使用，在bat中用start kugoumusicapi.exe启动，获取url的接口无法获取vip音乐url（已经登录且有vip），并且之后再次双击启动仍然无法正常使用。再次打包新的exe后双击启动可以正常使用，但是需要重新登录
http://localhost:3000/song/url?hash=7C874FFC2B38F4183007E8CBA3775099
歌名：只字不提

{
    "priv_status": 0,
    "hash_offset": {
        "start_byte": 0,
        "end_ms": 60000,
        "end_byte": 960151,
        "file_type": 0,
        "start_ms": 0,
        "offset_hash": "9285802AE045CC91E5FF1E7CFA3057D4"
    },
    "trans_param": {
        "classmap": {
            "attr0": 234881032
        },
        "display": 0,
        "display_rate": 0
    },
    "status": 2,
    "fail_process": [
        "pkg",
        "buy"
    ]
}

**Comment by ywd1988** [comment]
我通过写的中间件，请求后也是这个样子。

**Comment by starfish122** [comment]
因为打包时没有把.env文件打包进去，所以打包后的exe使用的是普通版而不是概念版，把.env文件打包进去并且保证加载到就好了
