### ISSUE TITLE
mixsongid获取

### ISSUE THREAD

**Issue by UzumakiHan** [MakcRe/KuGouMusicApi#48]
大佬好，mixsongid要从哪里获取，查看文档暂时没找到
![image](https://github.com/user-attachments/assets/c4dd109e-a6d5-4ff4-af14-1d1570251e1e)

**Comment by MakcRe** [comment]
能获取到音乐的基本都能获取到，有一些返回的是album_audio_id，传这个一样可以获取到

**Comment by MakcRe** [comment]
或者你可以通过 /privilege/lite 这个接口获取

**Comment by UzumakiHan** [comment]
> 能获取到音乐的基本都能获取到，有一些返回的是album_audio_id，传这个一样可以获取到

这个可以获取，感谢。
