### ISSUE TITLE
音乐图片的url失效，全都是无效图片

### ISSUE THREAD

**Issue by starfish122** [MakcRe/KuGouMusicApi#49]
例如通过获取歌单音乐的接口获得的音乐数据中 "union_cover":"http://imge.kugou.com/stdmusic/{size}/20161105/20161105090238303020.jpg",
"cover":"http://imge.kugou.com/stdmusic/{size}/20161105/20161105090238303020.jpg",
获得的都是这张图片
![Uploading 20161105090238303020.jpg…]()
{
                "bpm": 127,
                "hash": "937237F2C50B59D2CE73D67245099D04",
                "singerinfo": [
                    {
                        "type": 2,
                        "name": "lol",
                        "id": 191822,
                        "publish": 1
                    }
                ],
                "media_pay_type": 3,
                "audio_id": 24330050,
                "mvtrack": 3,
                "is_publish": 1,
                "name": "lol - sync.mp3",
                "hash_exist": 1,
                "publish_date": "2016-12-14",
                "rcflag": 1,
                "mvhash": "E86BBE190DCDE067B514A773F5F476E5",
                "collecttime": 1729769999,
                "csong": 0,
                "tagmap": {
                    "genre0": 69730305
                },
                "media_old_cpy": 0,
                "mvdata": [
                    {
                        "typ": 0
                    }
                ],
                "timelen": 263758,
                "media_type": "audio",
                "size": 4220755,
                "bpm_type": "3",
                "trans_param": {
                    "ogg_128_hash": "21B479CAC24FE7874C375418255DE40C",
                    "classmap": {
                        "attr0": 235012104
                    },
                    "language": "日语",
                    "cpy_attr0": 15488,
                    "musicpack_advance": 1,
                    "ogg_128_filesize": 3203816,
                    "display_rate": 2,
                    "union_cover": "http://imge.kugou.com/stdmusic/{size}/20161105/20161105090238303020.jpg",
                    "qualitymap": {
                        "attr0": 319864884
                    },
                    "pay_block_tpl": 1,
                    "display": 8,
                    "cid": 6713362,
                    "ipmap": {
                        "attr0": 2148537348
                    },
                    "hash_multitrack": "39B43AD7E85ED933EA276839C5FE833D",
                    "ogg_320_hash": "5F66A05C92EBDA1DC93A223C2BD194E9",
                    "hash_offset": {
                        "clip_hash": "6841B0BD6A1CCB9D4156158F069FA5C9",
                        "start_byte": 0,
                        "file_type": 0,
                        "end_byte": 480310,
                        "end_ms": 30000,
                        "start_ms": 0,
                        "offset_hash": "934FEAC05A86817CB6D948D89DE892BB"
                    },
                    "cpy_level": 1,
                    "cpy_grade": 5,
                    "ogg_320_filesize": 11590024
                },
                "fileid": 2,
                "sort": 10,
                "albuminfo": {
                    "publish": 1,
                    "name": "bye bye",
                    "category": 1,
                    "id": 1976755
                },
                "album_id": "1976755",
                "media_fail_process": 4,
                "media_privilege": 10,
                "cover": "http://imge.kugou.com/stdmusic/{size}/20161105/20161105090238303020.jpg",
                "mixsongid": 79986663,
                "bitrate": 128,
                "language": "日语",
                "mvtype": 1
            },

**Comment by MakcRe** [comment]
你把链接中的 {size} 去掉试一下？

**Comment by starfish122** [comment]
> 你把链接中的 {size} 去掉试一下？

可以了
