### ISSUE TITLE
获取歌单音乐列表失效了

### ISSUE THREAD

**Issue by 2900037917** [MakcRe/KuGouMusicApi#7]

**Comment by MakcRe** [comment]
我这边测试了一下是可以正常获取到歌单的音乐列表的，看一下参数是否错误了，文档里面中的调用例子出错了，参数是id不是ids

**Comment by 2900037917** [comment]
> 我这边测试了一下是可以正常获取到歌单的音乐列表的，看一下参数是否错误了，文档里面中的调用例子出错了，参数是id不是ids

噢噢原来如此，好的👌
