### ISSUE TITLE
定时调用刷新接口，token 还是一天就失效。

### ISSUE THREAD

**Issue by 13627491210** [MakcRe/KuGouMusicApi#8]
登录成功之后会返回一个 token，并且会临时保存到cookie, 目前 KG 刷新登录的方法是调用 login_by_token，应接口为 /login/token，该接口要传之前的登录的token和用户的userid

----------
大佬，按照上面你给的方式处理了，甚至定时每隔 3/4/5/6H 都试了。 调用 /login/token 接口，过大概一天就失效了，请问是什么原因？所以我现在每天都需要登录一下才行  @MakcRe

**Comment by MakcRe** [comment]
我这边测试过没发现这个问题， 调用 /login/token 接口后返回的数据的是什么

**Comment by MakcRe** [comment]
KG登陆好像是有设备数量限制的，你也可以看一下是否被别的设备顶下线了

**Comment by 13627491210** [comment]
> 我这边测试过没发现这个问题， 调用 /login/token 接口后返回的数据的是什么



调用 /login/token 接口 返回的token 和  调用登录接口返回的token一样 。 调用  /login/token 那个cookie 要不要传

**Comment by 13627491210** [comment]
> KG登陆好像是有设备数量限制的，你也可以看一下是否被别的设备顶下线了

没这个情况，定时刷新token 一般设置多久调用一次呢

**Comment by MakcRe** [comment]
> > 我这边测试过没发现这个问题， 调用 /login/token 接口后返回的数据的是什么
> 
> 
> 
> 
> 
> 
> 
> 调用 /login/token 接口 返回的token 和  调用登录接口返回的token一样 。 调用  /login/token 那个cookie 要不要传 

那你这个token应该是没有失效的，还是可以用的

**Comment by MakcRe** [comment]
能正常返回用户信息，token应该还是可以用的，token失效了就无法正常返回用户信息了

**Comment by MakcRe** [comment]
> > KG登陆好像是有设备数量限制的，你也可以看一下是否被别的设备顶下线了
> 
> 
> 
> 没这个情况，定时刷新token 一般设置多久调用一次呢

token具体能用多长时间没测试过，不过我3、4天调用一次也是可以的
